/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package regEx.practice;

import java.util.regex.Pattern;

public class RegularExpressionPractice {

    public String validateCreditCard(String creditCard) {
        String number = removeWhiteSpacesAndDashes(creditCard);
        String cardProvider = "";
        if (Pattern.matches("^4[0-9]{12}(?:[0-9]{3})?$",number)) {
            cardProvider = "VISA";
        }else if (Pattern.matches("^(?:5[1-5][0-9]{2}|222[1-9]|22[3-9][0-9]|2[3-6][0-9]{2}|27[01][0-9]|2720)[0-9]{12}$", number)){
            cardProvider = "MasterCard";
        }else{
            cardProvider = "Not a valid Card Number";
        }
        return cardProvider;
    }
    private String removeWhiteSpacesAndDashes(String number){
        return number.replaceAll("[ -/]","");
    }
}
