/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package regEx.practice;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class CreditCardValidatorTest {

    private CreditCardValidator regEx;

    @Before
    public void setup(){
        regEx = new CreditCardValidator();
    }

    @Test
    public void is_ValidVisa() {
        String visa = "4123-1234-2500-0966";
        String fake = "3123 2222 0000 53";

        assertEquals("VISA",regEx.validateCreditCard(visa));
        assertEquals("Not a valid Card Number", regEx.validateCreditCard(fake));
    }

    @Test
    public void is_ValidMasterCard(){
        String mc = "2223 8989 0900 7897";
        String fake = "3123 2222 0000 53";

        assertEquals("MasterCard", regEx.validateCreditCard(mc));
        assertEquals("Not a valid Card Number", regEx.validateCreditCard(fake));
    }

    @Test
    public void is_ValidAmericanExpress(){
        String aEx = "373 8989 0900 7897";
        String fake = "3123 2222 0000 53";

        assertEquals("AmericanExpress", regEx.validateCreditCard(aEx));
        assertEquals("Not a valid Card Number", regEx.validateCreditCard(fake));
    }

    @Test
    public void is_ValidDiscover(){
        String dsc = "65 8989 0900 7897 99";
        String fake = "3123 2222 0000 53";

        assertEquals("Discover", regEx.validateCreditCard(dsc));
        assertEquals("Not a valid Card Number", regEx.validateCreditCard(fake));
    }

    @Test
    public void is_ValidJCB(){
        String jcb = "2131 8989 0900 789";
        String jcb2 = "35 6785 8765 8976 67";
        String fake = "3123 2222 0000 53";

        assertEquals("JCB", regEx.validateCreditCard(jcb));
        assertEquals("JCB", regEx.validateCreditCard(jcb2));
        assertEquals("Not a valid Card Number", regEx.validateCreditCard(fake));
    }
}
