/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package regEx.practice;

import org.junit.Test;
import static org.junit.Assert.*;

public class RegularExpressionTest {

    @Test
    public void is_CreditCardNumber_ValidVisa() {
        RegularExpression regEx = new RegularExpression();
        String visa = "4123-1234-2500-0966";
        String fake = "3123 2222 0000 53";
        assertEquals("VISA",regEx.validateCreditCard(visa));
        assertEquals("Not a valid Card Number", regEx.validateCreditCard(fake));
    }
}
